### ISSUE TITLE
An alternate branch using Dagger Hilt instead of Kodein in this repo

### ISSUE THREAD

**Issue by donenoyes** [programadorthi/android-super-app#1]
Dagger Hilt is the recommended solution. It would be helpful if you could create an alternate branch to showcase usage of Dagger Hilt instead of Kodein.

**Comment by programadorthi** [comment]
Since Koin and Kodein was created I haven't used Dagger anymore.
I`ll try but don't wait because this projects will be converted do Multiplatform where Koin and Kodein have support already.

**Comment by programadorthi** [comment]
@donenoyes check the branch [main-hilt](https://github.com/programadorthi/android-super-app/tree/main-hilt). The solution is not perfect but the main reason is Hilt complexity.
